name: Manual Docker Deploy to Render

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'pr5/**'

env:
  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
  DOCKER_IMAGE_NAME: kurochkinvadim/pr5-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: ./pr5
        run: |
          docker build -t $DOCKER_IMAGE_NAME:$GITHUB_SHA .

      - name: Login to Docker Hub
        run: echo '${{ secrets.DOCKER_HUB_TOKEN }}' | docker login -u '${{ secrets.DOCKER_HUB_USERNAME }}' --password-stdin

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE_NAME:$GITHUB_SHA

      - name: Trigger Render Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/pr5-app
        run: |
          # Формируем JSON-тело с правильной подстановкой переменных
          JSON_BODY=$(jq -n \
            --arg image "$DOCKER_IMAGE_NAME:$GITHUB_SHA" \
            '{
              "clearCache": true,
              "image": $image
            }')
    
          echo "Отправляемый JSON: $JSON_BODY"
    
          # Отправка запроса
          curl -v -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$JSON_BODY" \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"
